name: kata

on:
  push:
    branches: [ kata ]

env:
  GO111MODULE: on 
  PROJECT: kata-containers
  BRANCH: stable-2.5
  RUSTUP_DIST_SERVER: "https://mirrors.ustc.edu.cn/rust-static"
  RUSTUP_UPDATE_ROOT: "https://mirrors.ustc.edu.cn/rust-static/rustup"

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [self-hosted]
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.68.2
        override: true

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"

    - name: Set up Go 1.22
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Check out repo code
      uses: actions/checkout@v2

    - name: Check out build code
      uses: actions/checkout@v2
      with:
        repository: liangjingtao11/kata-containers
        ref: ${{ env.BRANCH }}
        token: ${{ secrets.KUBERNETESPULL }}
        path: ${{ env.PROJECT }}

    - name: Set up Docker Buildx
      if: matrix.os != 'self-hosted'
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build image
      run: |
        cd ${{ env.PROJECT }}/ecr_deploy
        make -f ../../kata-image/kata-image.mk all
